---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-snapshot
  namespace: kube-system
spec:
  schedule: "15 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etcd
              # Same image as in /etc/kubernetes/manifests/etcd.yaml
              image: k8s.gcr.io/etcd
              env:
                - name: ETCDCTL_API
                  value: "3"
                - name: BACKUP_DIR
                  value: "/kubernetes/backup"
              command: ["/bin/sh"]
              args: ["-c", "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key snapshot save $BACKUP_DIR/etcd-$(date +%Y-%m-%d_%H-%M-%S_%Z).db && find $BACKUP_DIR -name \"etcd-*.db\" -type f -mtime +30 -exec rm {} \\;"]
              volumeMounts:
                - mountPath: /etc/kubernetes
                  name: etckubernetes
                  readOnly: true
                - mountPath: /kubernetes/backup
                  name: kubernetesbackup
            - name: pki
              image: k8s.gcr.io/etcd
              env:
                - name: BACKUP_DIR
                  value: "/kubernetes/backup"
              command: ["/bin/sh"]
              args: ["-c", "cp -av /etc/kubernetes/pki $BACKUP_DIR/pki-$(date +%Y-%m-%d_%H-%M-%S_%Z) && find $BACKUP_DIR -maxdepth 1 -name \"pki-*\" -type d -ctime +30 -exec rm -vrf {} \\;"]
              volumeMounts:
                - mountPath: /etc/kubernetes
                  name: etckubernetes
                  readOnly: true
                - mountPath: /kubernetes/backup
                  name: kubernetesbackup
          hostNetwork: true
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: node-role.kubernetes.io/master
                      operator: Exists
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: etckubernetes
              hostPath:
                path: /etc/kubernetes
                type: Directory
            - name: kubernetesbackup
              hostPath:
                path: /kubernetes/backup
                type: DirectoryOrCreate
