apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SERVER_DOMAIN
              value: grafana.local.io
                #- name: GF_SERVER_ROOT_URL
                #  value: root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
                #- name: GF_SERVER_SERVE_FROM_SUB_PATH
                #  value: "true"
          volumeMounts:
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: provisioning-datasources
          configMap:
            name: provisioning-datasources
        - name: data
          persistentVolumeClaim:
            claimName: grafana-storage

