apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitor
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitor
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
