---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ${ES_HOST:127.0.0.1}
  port: ${ES_PORT:9200}
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  username:
  password:
  timeout: 30
  master_only: False

logging:
  loglevel: ${LOG_LEVEL:INFO}
  logfile:
  logformat: ${LOG_FORMAT:default}
  blacklist: ['elasticsearch', 'urllib3']
