apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: metrics
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: metrics
  ports:
    - port: 9090
      targetPort: 9090
