apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
  type: ClusterIP
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
