apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-storage
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /kube/elasticsearch/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node.local.io/elasticsearch-storage
            operator: In
            values:
              - local
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-storage
    namespace: logging

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-storage
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
spec:
  volumeName: elasticsearch-storage
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
