namespace: ingress-nginx
resources:
  - ../manifests
patchesStrategicMerge:
  - manifests/controller-service.yaml
  - manifests/controller-deployment.yaml
configMapGenerator:
  - name: ingress-nginx-controller
    namespace: ingress-nginx
    behavior: merge
    literals:
        # https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address
        # Sets the header field for identifying the originating IP address of a client.
        # default: X-Forwarded-For
        # forwarded-for-header=X-Forwarded-For

        # If true, NGINX passes the incoming X-Forwarded-* headers to upstreams.
        # Use this option when NGINX is behind another L7 proxy / load balancer
        # that is setting these headers.
        #
        # If false, NGINX ignores incoming X-Forwarded-* headers, filling them
        # with the request information it sees. Use this option if NGINX is
        # exposed directly to the internet, or it's behind a L3/packet-based
        # load balancer that doesn't alter the source IP in the packets.
      - use-forwarded-headers="true"

        # Append the remote address to the X-Forwarded-For header instead of replacing it.
        # When this option is enabled, the upstream application is responsible for 
        # extracting the client IP based on its own list of trusted proxies.
      - compute-full-forwarded-for=true

        # Enables or disables the header HSTS in servers running SSL. 
        # HTTP Strict Transport Security(often abbreviated as HSTS) is a 
        # security feature (HTTP header) that tell browsers that 
        # it should only be communicated with using HTTPS, 
        # instead of using HTTP. It provides protection against protocol downgrade attacks and cookie theft.
        # 
        # References:
        # 
        #   https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security
        #   https://blog.qualys.com/securitylabs/2016/03/28/the-importance-of-a-proper-http-strict-transport-security-implementation-on-your-web-server
      - hsts=false

        # Enables or disables the use of HSTS in all the subdomains of the server-name.
      - hsts-include-subdomains=true

        # Sets the time, in seconds, that the browser should remember that this site is only to be accessed using HTTPS.
        # - hsts-max-age=0
      - hsts-max-age=15724800

        # Enables or disables the preload attribute in the HSTS feature (when it is enabled).
      - hsts-preload=false

        # Adds an X-Original-Uri header with the original request URI to the backend request
      - proxy-add-original-uri-header=false
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: registry.k8s.io/ingress-nginx/controller
    newName: registry.aliyuncs.com/google_containers/nginx-ingress-controller
    # remove the digest to ignore the integrity checking.
    newTag: v1.9.6
  - name: registry.k8s.io/ingress-nginx/kube-webhook-certgen
    newName: registry.aliyuncs.com/google_containers/kube-webhook-certgen
    # remove the digest to ignore the integrity checking.
    newTag: v20231226-1a7112e06
