namespace: monitor
resources:
  - ../../../../manifests/grafana
  - manifests/ingress.yaml
patches:
  - manifests/deployment-env.yaml
  - manifests/deployment-volumes.yaml
configMapGenerator:
  - name: provisioning-datasources
    files:
      - manifests/provisioning/datasources/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
