apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - namespace.yaml
  - configmap.yaml
  - rbac.yaml
  - daemonset.yaml
  - default-http-backend.yaml
