apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../manifests
  - overlays/manifests/ingress.yaml
patchesStrategicMerge:
  - overlays/manifests/deployment.yaml
secretGenerator:
  - name: local.io
    files:
      - tls.crt=overlays/manifests/tls/local.io.crt
      - tls.key=overlays/manifests/tls/local.io.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: k8s.gcr.io/echoserver
    newName: registry.aliyuncs.com/google_containers/echoserver
    newTag: "1.10"
