apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitor
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 2000m
              memory: 4Gi
              ephemeral-storage: 10Gi
