---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node.efk.io/elasticsearch-storage-ready
                  operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - elasticsearch
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: elasticsearchdata
          hostPath:
            path: /home/elasticsearch
            type: DirectoryOrCreate
      containers:
        - name: elasticsearch
          resources:
            # need more cpu upon initialization, therefore burstable class
            requests:
              cpu: 1000m
              memory: 5000Mi
            limits:
              cpu: 4000m
              memory: 6000Mi
          env:
            - name: "discovery.type"
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms4g -Xmx4g"

      initContainers:
        # The container runs Elasticsearch as user elasticsearch using uid:gid 1000:1000.
        # Bind mounted host the data and log dirs, such as
        # /usr/share/elasticsearch/data, write access is required as well.
        - image: alpine:3.6
          name: elasticsearch-data-dir-init
          env:
            - name: datadir
              value: /home/elasticsearch
          command:
            - "/bin/sh"
            - "-c"
            - "if [ -d ${datadir} ] && [ ! -d ${datadir}/nodes ]; then chown 1000:1000 ${datadir}; fi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearchdata
              mountPath: /home/elasticsearch
