apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - ../../manifests/namespace
  - ./prometheus
  - ./grafana
  - ./kube-state-metrics
  - ./node-exporter
