apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  labels:
    app.kubernetes.io/name: prometheus-server
    app.kubernetes.io/part-of: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-server
      app.kubernetes.io/part-of: monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-server
        app.kubernetes.io/part-of: monitor
    spec:
      serviceAccountName: prometheus-server
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: prometheus-server
          image: prom/prometheus:v2.31.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.no-lockfile"
            - "--log.level=error"
            - "--log.format=json"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            timeoutSeconds: 5
          #readinessProbe:
          #  httpGet:
          #    path: /-/ready
          #    port: 9090
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 5
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-configuration
