---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../base
patchesStrategicMerge:
  - metrics-server-deployment.yaml
images:
  - name: k8s.gcr.io/metrics-server-amd64
    newTag: "v0.3.6"
