apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - namespace.yaml
  - kube-state-metrics/cluster-role-binding.yaml
  - kube-state-metrics/cluster-role.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service-account.yaml
  - kube-state-metrics/service.yaml
  - prometheus/rbac.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
configMapGenerator:
  - name: prometheus-configuration
    files:
      - prometheus/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
