apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../base
images:
  - name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    newTag: 0.26.1
  - name: qqbuby/nginx-ingress-controller-default-backend
    newTag: 1.17.5
