apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP  
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
