apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: metrics
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SERVER_DOMAIN
              value: grafana.local.io
                #- name: GF_SERVER_ROOT_URL
                #  value: root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
                #- name: GF_SERVER_SERVE_FROM_SUB_PATH
                #  value: "true"
