apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  template:
    spec:
      containers:
        - name: echoserver
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
              ephemeral-storage: 5Mi
            limits:
              cpu: 50m
              memory: 50Mi
              ephemeral-storage: 10Mi
