{
 "title": "Kubernetes Monitor",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Network/ Filesystem usage as well as individual pod, containers statistics. Uses cAdvisor and kube-state metrics only.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[$__rate_interval])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) / sum (machine_cpu_cores{})",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", node=~\"^$Node$\"}[$__rate_interval])) by (node) / sum (machine_cpu_cores{node=~\"^$Node$\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes{}) * 100",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) by (node) / sum (machine_memory_bytes{node=~\"^$Node$\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) * 100",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{node=~\"^$Node$\"}[$__rate_interval])) by (node)",
       "legendFormat": "-> {{node}}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{node=~\"^$Node$\"}[$__rate_interval])) by (node)",
       "legendFormat": "<- {{node}}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{node=~\"^$Node$\"}[$__rate_interval]))",
       "legendFormat": "-> Cluster"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{node=~\"^$Node$\"}[$__rate_interval]))",
       "legendFormat": "<- Cluster"
      }
     ]
    },
    {
     "title": "Filesystem I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"^$Node$\"}[$__rate_interval])) by (node)",
       "legendFormat": "-> {{node}}"
      },
      {
       "expr": "- sum(rate(container_fs_reads_bytes_total{node=~\"^$Node$\"}[$__rate_interval])) by (node)",
       "legendFormat": "<- {{node}}"
      }
     ]
    },
    {
     "title": "Filesystem Capacity usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{node=~\"^$Node$\"}) by (node)",
       "legendFormat": " {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numbers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(kube_node_info)", "legendFormat": "Total" },
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "CPU requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{exported_node=~\"^$Node$\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{exported_node=~\"^$Node$\",resource=\"memory\"}) / sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{exported_node=~\"^$Node$\",condition=\"DiskPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Memory Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{exported_node=~\"^$Node$\",condition=\"MemoryPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "PID Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{exported_node=~\"^$Node$\",condition=\"PIDPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "CPU limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{exported_node=~\"^$Node$\",resource=\"cpu\"}) / sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{exported_node=~\"^$Node$\",resource=\"memory\"}) / sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Unschedulable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{exported_node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{exported_node=~\"^$Node$\",condition=\"OutOfDisk\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Network Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{exported_node=~\"^$Node$\",condition=\"NetworkUnavailable\",status!=\"false\"})"
      }
     ]
    },
    {
     "title": "CPU Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{exported_node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{exported_node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Memory Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{exported_node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{exported_node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Storage Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{exported_node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{exported_node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{exported_node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top-5 Deployment status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,kube_deployment_status_replicas_ready/(kube_deployment_status_replicas>0))",
       "legendFormat": "{{namespace}}/{{ deployment }}"
      }
     ]
    },
    {
     "title": "Top-5 Daemonset status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,kube_daemonset_status_number_ready/(kube_daemonset_status_desired_number_scheduled>0))",
       "legendFormat": "{{namespace}}/{{ daemonset}}"
      }
     ]
    },
    {
     "title": "Top-5 Job Status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,sum(kube_job_status_succeeded / kube_job_spec_completions) by (job_name,namespace))",
       "legendFormat": "{{namespace}}/{{ job_name}}"
      }
     ]
    },
    {
     "title": "Pod  status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Container status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running)",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting)",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated)",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "CPU vCores Requested by Pod",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "suffix:m" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory  Requested by Pod",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Top-10 Pod Restarts (Last 30 Minutes)",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total[30m])) by (pod)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU / Memory / Network / Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"^$Node$\",image!=\"\",container!=\"POD\",container!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"^$Node$\",image!=\"\",container!=\"POD\",container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Network I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{node=~\"^$Node$\",image!=\"\",container=~\"^(POD)?$\"}[$__rate_interval])) by (pod)",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{node=~\"^$Node$\",image!=\"\",container=~\"^(POD)?$\"}[$__rate_interval])) by (pod)",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    },
    {
     "title": "Pod Filesystem I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"^$Node$\",pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "-sum(rate(container_fs_reads_bytes_total{node=~\"^$Node$\",pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container CPU / Memory / Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"^$Node$\",image!=\"\",container!=\"POD\",container!=\"\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "{{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Container Memory  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{node=~\"^$Node$\",image!=\"\",container!=\"POD\",container!=\"\"}) by (pod,container)",
       "legendFormat": "{{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Container Filesystem I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"^$Node$\",pod!=\"\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "-> {{ pod}} | {{container}}"
      },
      {
       "expr": "-sum(rate(container_fs_reads_bytes_total{node=~\"^$Node$\",pod!=\"\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "<- {{ pod}} | {{container}}"
      }
     ]
    }
   ]
  }
 ]
}