apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manifests/namespace
  - ../manifests/local-storage
  - manifests/prometheus
  - manifests/grafana
  - manifests/kube-state-metrics
  - manifests/node-exporter
images:
  - name: registry.k8s.io/kube-state-metrics/kube-state-metrics
    newName: bitnami/kube-state-metrics
    newTag: 2.10.1
  - name: prom/prometheus
    newTag: v2.50.1
  - name: prom/node-exporter
    newTag: v1.7.0
  - name: grafana/grafana-oss
    newTag: 10.2.4
