---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  labels:
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: monitor
  annotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: monitor
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
