apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
  - ../../../manifests/grafana
  - manifests/ingress.yaml
patches:
  - path: manifests/deployment-env.yaml
  - path: manifests/deployment-volumes.yaml
configMapGenerator:
  - name: provisioning-datasources
    files:
      - manifests/provisioning/datasources/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
