---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-swagger-ui
  name: kube-swagger-ui
spec:
  type: ClusterIP
  selector:
    app: kube-swagger-ui
  ports:
    - port: 80
      protocol: TCP
      targetPort: swagger-ui
