apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../manifests
  - manifests/ingress.yaml
patches:
  - path: manifests/deployment.yaml
secretGenerator:
  - name: local.io
    files:
      - tls.crt=manifests/tls/local.io.crt
      - tls.key=manifests/tls/local.io.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: registry.k8s.io/echoserver
    newName: registry.aliyuncs.com/google_containers/echoserver
    newTag: "1.10"
