apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
commonLabels:
  app.kubernetes.io/part-of: metrics
resources:
  - manifests/rbac.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
configMapGenerator:
  - name: prometheus-configuration
    files:
      - manifests/config/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
