apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysqld-exporter
    app.kubernetes.io/part-of: monitor
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
  name: mysqld-exporter
spec:
  selector:
    app.kubernetes.io/name: mysqld-exporter
  type: ClusterIP  
  ports:
    - port: 9104
      protocol: TCP
      targetPort: 9104
