apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  template:
    spec:
      volumes:
        - name: elasticsearchdata
          persistentVolumeClaim:
            claimName: elasticsearch-storage
      containers:
        - name: elasticsearch
          volumeMounts:
            - name: elasticsearchdata
              mountPath: /usr/share/elasticsearch/data
