apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        fluentbit.io/parser_stdout: ingressnginx
    spec:
      containers:
        - name: controller
          ports:
            - name: prometheus
              containerPort: 10254
              protocol: TCP
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - topologyKey: kubernetes.io/hostname
#              labelSelector:
#                matchLabels:
#                  app.kubernetes.io/component: controller
#                  app.kubernetes.io/instance: ingress-nginx
#                  app.kubernetes.io/name: ingress-nginx
