apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitor
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /kube/grafana/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node.local.io/grafana-storage
            operator: In
            values:
              - local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitor
spec:
  volumeName: grafana-storage
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
