apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: metrics
spec:
  template:
    spec:
      containers:
        - name: prometheus
          # --web.enable-lifecycle     Enable shutdown and reload via HTTP request.
          # --web.enable-admin-api     Enable API endpoints for admin control actions.
          # --query.max-samples=50000000
          #     Maximum number of samples a single query can
          #     load into memory. Note that queries will fail
          #     if they try to load more samples than this into
          #     memory, so this also limits the number of
          #     samples a query can return.
          # --query.timeout=2m         Maximum time a query may take before being aborted.
          # --query.max-concurrency=20 Maximum number of queries executed concurrently.
          # --log.level=info           Only log messages with the given severity or above. One of: [debug, info, warn, error]
          # --log.format=logfmt        Output format of log messages. One of: [logfmt, json]
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.no-lockfile"
            - "--storage.tsdb.retention.time=365d"
            - "--storage.tsdb.retention.size=384GB"
            - "--log.level=warn"
            - "--log.format=logfmt"
