apiVersion: v1
kind: Service
metadata:
  name: internal-echoserver
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-private-eastus2"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # loadBalancerIP: 10.100.1.25
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: echoserver
