apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
  ports:
    - port: 5601
      protocol: TCP
