apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - ../../../manifests/grafana
  - manifests/ingress.yaml
patchesStrategicMerge:
  - manifests/deployment-env.yaml
  - manifests/deployment-volumes.yaml
configMapGenerator:
  - name: provisioning-datasources
    files:
      - manifests/provisioning/datasources/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
