apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
              ephemeral-storage: 10Gi
            limits:
              cpu: 1000m
              memory: 1000Mi
              ephemeral-storage: 10Gi
