---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    k8s-app: kibana
    kubernetes.io/name: "Kibana"
spec:
  type: NodePort
  selector:
    k8s-app: kibana
  ports:
    - port: 5601
      nodePort: 32115
      protocol: TCP
      targetPort: ui
