apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - namespace.yaml
  - elasticsearch-sts.yaml
  - es-curator-cronjob.yaml
  - fluent-bit-ds.yaml
  - fluent-bit-role-binding.yaml
  - fluent-bit-role.yaml
  - fluent-bit-service-account.yaml
  - kibana-deploy.yaml
  - kibana-service.yaml
